### ISSUE TITLE
http/2 with alpn-agent + jetty

### ISSUE THREAD

**Issue by otrosien** [making/demo-http2#4]
Hi,
I continued working on my fork of the http2-demo, and at the moment I have a working integration using jetty-9.3 + using the improved registration of the alpn-boot library using a javaagent. 

I don't know how much sense it would make to re-unite this into one project, or you could just link to my project.

Here's my fork: https://github.com/otrosien/demo-http2

Regards,
 Oliver

**Comment by making** [comment]
Added in README :)
